### ISSUE TITLE
Verification of updates for Load and Store Statements

### ISSUE THREAD

**Issue by 42niks** [CompL-IITMandi/stava#3]
For Store statements of type `a.f = b`, changes to be made are:
`es(a)` to be copied into `es(b)` and all objects reachable from `b`.

For Load statements of type `b = a.f`, changes to be made are:
1. If `a.f` already exists: 
`b -> [assimilate all objects pointed to by a.f]`. Should a new object be created here?
2. if `a.f` doesn't already exist: (can `a` be a field variable in such a case?) 
`a.f -> [new object]`
`b -> [same new object]`
`es(same new object) = es(a).f`

**Comment by 42niks** [comment]
is there any meaning of strong update for a store statement? If yes, how can it be achieved?

**Comment by 42niks** [comment]
What must be done for a combination of Store and Erase statement?
Example: `a.f = null`
Should it follow with a strong update if and only if both are set to `UpdateType.STRONG` or something else? @manasthakur

**Comment by manasthakur** [comment]
Answering the last question first: For `a.f = null`, ideally we should assign to `a.f` an object that represents `null`. Without strong updates, we shouldn't kill the previous information. Such a special object could be a single universal one. I think its escape status could be `DoesNotEscape`.

Second last: For understanding the crux of strong updates, please see the first few slides at https://www.cs.utexas.edu/users/isil/esop2010-talk.pdf

**Comment by 42niks** [comment]
@manasthakur What must be the behavior of this `NullObject`? 
1. Field Objects:
If we allow it to have field objects, it carries no meaning. If we don't allow it to have field objects, then what are we supposed to do at this situation:
```
a.f = null // a.f now has only a single object, NullObject, in its points-to set.
... // Uncaptured ReAssignment
b = a.f // the load statements assimilate the field objects. Now points-to set of b will have null object.
// a.f has been reassigned a new valid object which means now b will actually point to legitimate object at runtime
b.s = new String("") // what do we do now?
```

2. Escape status:
```
a.f = null // adds null object to a.f
b.s = null // adds null object to b.s. Note that it will be same object due to singleton design.
foo(a.f) // add CV <foo,<parameter,0>.f> to es(NullObject)? 
// if yes, then inadvertently, es(b.s) will also get a CV added even though it was never passed to foo.
```

In my opinion, for weak updates, we should let `a.f` be as it is and ensure at least an empty points-to set exists in the graph (actually a map). For strong update, we can clear an existing points-to set, or at least ensure an empty points-to set.

**Comment by manasthakur** [comment]
I think your proposal sounds fine.
