### ISSUE TITLE
BCIs for `newarray/anewarray/*newmultiarray` etc are incorrect

### ISSUE THREAD

**Issue by manasthakur** [CompL-IITMandi/stava#8]
Looks like the BCIs for array allocations are being picked up from the next statement (found in moldyn/md.runiters).

Plan: Check this with a small program involving different kinds of array allocations.

Solution(s): Perhaps get the BCI of the predecessor from the control-flow graph? Else subtract correct offset based on the kind of array-alloc instruction.

**Comment by dheeraj135** [comment]
Fixed by #9 .
